### ISSUE TITLE
Japan yahoo data extraction failure

### ISSUE THREAD

**Issue by dcgithubaccount** [dcgithubaccount/TechnicalIndicators#3]
Japan nikkei data when downloaded individually has no issues but when it is called from TechnicalIndicator.py it fails to download historical data. 

_Please use below code to reproduce the issue_ 

` import pandas_datareader.data as web`
 `import datetime`
`import pandas as ps`
`import numpy as np`
`d=datetime.datetime.today()`
`prevDay = d`
`minusYear = datetime.timedelta(days=365)`
`oneYearBeforeDate = prevDay - minusYear`
`start = datetime.datetime(oneYearBeforeDate.year,`
`...                               oneYearBeforeDate.month, oneYearBeforeDate.day)`
`end = datetime.datetime(prevDay.year, prevDay.month, prevDay.day)`
`f = web.DataReader('4578', 'yahoo', start, end)`
`f`

**Comment by dcgithubaccount** [comment]
When i ran below piece of code, it gave me this error. It seems the error is happening because Yahoo Ticker for Japan is Int where as it should be Str. 

_It should be tested with str._

`a = [x  for x in stx['Yahoo Ticker']]`
`a[0]`
`f = web.DataReader(a[0],'yahoo',start,end)`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/data.py", line 94, in DataReader
    session=session).read()
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/yahoo/daily.py", line 77, in read
    df = super(YahooDailyReader, self).read()
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 178, in read
    df = self._dl_mult_symbols(self.symbols)
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 185, in _dl_mult_symbols
    for sym_group in _in_chunks(symbols, self.chunksize):
  File "/spare/Anaconda/lib/python3.5/site-packages/pandas_datareader/base.py", line 215, in _in_chunks
    return (seq[pos:pos + size] for pos in range(0, len(seq), size))
TypeError: object of type 'numpy.int64' has no len()
```
